### ISSUE TITLE
Cannot read properties of null (reading 'props')

### ISSUE THREAD

**Issue by goper-leo** [lepikhinb/momentum-modal#58]
Installed the package and [setup](https://github.com/lepikhinb/momentum-modal#installation) and also looked on the [examples](https://github.com/lepikhinb/momentum-modal-plugin/tree/master/examples) after running vite page go blank and a console error message.
```js
app.ts:131 Uncaught TypeError: Cannot read properties of null (reading 'props')
    at ReactiveEffect.fn (app.ts:131:38)
    at ReactiveEffect.run (reactivity.esm-bundler.js:190:25)
    at get value [as value] (reactivity.esm-bundler.js:1171:39)
    at Object.get2 [as get] (reactivity.esm-bundler.js:504:67)
    at ReactiveEffect.fn (momentum-modal.js:15:46)
    at ReactiveEffect.run (reactivity.esm-bundler.js:190:25)
    at get value [as value] (reactivity.esm-bundler.js:1171:39)
    at w (momentum-modal.js:44:26)
    at momentum-modal.js:51:1
```

`PHP`: `8.1.`
`Laravel`: `10x`
`Vite`: `4.2.2`
`Vue`: `3.2.47`
`@inertiajs/vue3`: `1.0.4`
`momentum-modal`: `0.2.1`
`based/momentum-modal`: `v0.2.0`

**Comment by goper-leo** [comment]
After hours debugging the issue was on my packages (`npm`). 
I just ran `npm update` and after that everything works!

I used **`laravel/breeze`** for initializing my project. Just added here if someone rans into it.

Thanks for this wonderful & helpful package!
